=== NCIP/catissue-utilities/caTissueLoader/xml/caTissueTextMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="columnMap">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dateFormat"/>
        <xs:element minOccurs="1" maxOccurs="3" ref="rowClass"/>
        <xs:element maxOccurs="unbounded" ref="column"/>
      </xs:sequence>
      <xs:attribute name="headerRow" use="required" type="xs:boolean"/>
      <xs:attribute name="fileType" use="required" type="fileType"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dateFormat" type="xs:string"/>
  <xs:element name="rowClass" type="xs:string"/>
  <xs:element name="column">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="valueMapping"/>
      </xs:sequence>
      <xs:attribute name="attributeName" use="required" type="attributeName"/>
      <xs:attribute name="columnNo" type="xs:integer"/>
      <xs:attribute name="fixedValue"/>
      <xs:attribute name="externalMapping" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="valueMapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="valueMap"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="valueMap">
    <xs:complexType>
      <xs:attribute name="fromValue" use="required"/>
      <xs:attribute name="ignoreCase"  type="xs:boolean"/>
      <xs:attribute name="toValue" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name = "rowClass">
    <xs:annotation>
      <xs:documentation>The class of object represented by a row</xs:documentation>
    </xs:annotation>
    <xs:restriction base = "xs:string">
      <xs:enumeration value = "Specimen"/>
      <xs:enumeration value = "Participant"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name = "fileType">
    <xs:annotation>
      <xs:documentation>A file type which can be imported</xs:documentation>
    </xs:annotation>
    <xs:restriction base = "xs:string">
      <xs:enumeration value = "xlText"/>
      <xs:enumeration value = "excelCSV"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name = "attributeName">
    <xs:annotation>
      <xs:documentation>A valid attribute name in caTissue</xs:documentation>
    </xs:annotation>
    <xs:restriction base = "xs:NCName">
      <xs:enumeration value = "availableQuantity"/>
      <xs:enumeration value = "birthDate"/>
      <xs:enumeration value = "calendarPoint"/>
      <xs:enumeration value = "clinicalDiagnosis"/>
      <xs:enumeration value = "clinicalStatus"/>
      <xs:enumeration value = "collectionProcedure"/>
      <xs:enumeration value = "container"/>
      <xs:enumeration value = "deathDate"/>
      <xs:enumeration value = "ethnicity"/>
      <xs:enumeration value = "firstName"/>
      <xs:enumeration value = "gender"/>
      <xs:enumeration value = "groupActivityStatus"/>
      <xs:enumeration value = "groupCollTime"/>
      <xs:enumeration value = "groupRecTime"/>
      <xs:enumeration value = "label"/>
      <xs:enumeration value = "lastName"/>
      <xs:enumeration value = "lineage"/>
      <xs:enumeration value = "medicalRecordNumber"/>
      <xs:enumeration value = "registrationDate"/>
      <xs:enumeration value = "middleName"/>
      <xs:enumeration value = "parentSpecimenLabel"/>
      <xs:enumeration value = "participantActivityStatus"/>
      <xs:enumeration value = "pathologicalStatus"/>
      <xs:enumeration value = "PPI"/>
      <xs:enumeration value = "protocolTitle"/>
      <xs:enumeration value = "quantity"/>
      <xs:enumeration value = "race"/>
      <xs:enumeration value = "race1"/>
      <xs:enumeration value = "race2"/>
      <xs:enumeration value = "race3"/>
      <xs:enumeration value = "race4"/>
      <xs:enumeration value = "receivedQuality"/>
      <xs:enumeration value = "regActivityStatus"/>
      <xs:enumeration value = "SCGName"/>
      <xs:enumeration value = "sexGenotype"/>
      <xs:enumeration value = "siteName"/>
      <xs:enumeration value = "socialSecurityNumber"/>
      <xs:enumeration value = "specCollTime"/>
      <xs:enumeration value = "specimenActivityStatus"/>
      <xs:enumeration value = "specimenCollectionStatus"/>
      <xs:enumeration value = "groupCollectionStatus"/>
      <xs:enumeration value = "specimenAvailable"/>
      <xs:enumeration value = "specimenType"/>
      <xs:enumeration value = "specRecTime"/>
      <xs:enumeration value = "tissueSide"/>
      <xs:enumeration value = "tissueSite"/>
      <xs:enumeration value = "userEmail"/>
      <xs:enumeration value = "vitalStatus"/>    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== NCIP/catissue-utilities/caTissueCoreLoader/examples/Patient2ColsMap.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
   Copyright Washington University in St. Louis
   Copyright SemanticBits
   Copyright Persistent Systems
   Copyright Krishagni

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/catissue-utilities/LICENSE.txt for details.
L-->

<columnMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xml/caTissueTextMap.xsd" 
    headerRow="true"
    fileType="xlText">

    <dateFormat>MM/dd/yyyy</dateFormat>
    <rowClass>Participant</rowClass>
    <column attributeName="protocolTitle" fixedValue="Demo of collection protocol"/>
    <column attributeName="PPI" columnNo="2"/>
    <column attributeName="gender" columnNo="1">  
        <valueMapping>
            <valueMap fromValue="F" ignoreCase="true" toValue="Female Gender"/>
            <valueMap fromValue="M" ignoreCase="true" toValue="Male Gender"/>
        </valueMapping>
    </column>
    <column attributeName="medicalRecordNumber" columnNo="2"/>
    <column attributeName="participantActivityStatus" fixedValue="Active"/>
    <column attributeName="regActivityStatus" fixedValue="Active"/>
    <column attributeName="siteName" fixedValue="Haven outpatients clinic"/>

</columnMap>

=== NCIP/catissue-utilities/trunk/caTissueCoreLoader/mappings/ethnicity/CDCEthnicityCodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<valueMapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../textdata/caTissueTextMap.xsd">
    <valueMap fromValue="E1" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.001" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.002" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.003" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.004" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.005" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.006" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.007" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.008" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.01.009" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.02" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.02.001" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.02.002" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.02.003" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.02.004" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.02.005" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.001" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.002" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.003" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.004" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.005" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.006" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.007" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.03.008" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.001" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.002" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.003" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.004" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.005" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.006" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.007" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.008" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.009" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.010" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.04.011" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.05" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.06" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.07" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E1.08" ignoreCase="true" toValue="Hispanic or Latino"/>
    <valueMap fromValue="E2" ignoreCase="true" toValue="Not Hispanic or Latino"/>
</valueMapping>

=== NCIP/catissue-utilities/caTissueCoreLoader/examples/SpecimenTextMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<columnMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xml/caTissueTextMap.xsd"
 headerRow="true"
 fileType="xlText">
    <dateFormat>MM/dd/yyyy</dateFormat>
    <rowClass>Specimen</rowClass>
    <rowClass>SpecimenCollectionGroup</rowClass>
    <column attributeName="protocolTitle" fixedValue="Demo of collection protocol"/>
    <column attributeName="PPI" columnNo="1"/>
    <column attributeName="calendarPoint" columnNo="2"/>
    <column attributeName="siteName" fixedValue="Haven outpatients clinic"/>
    <column attributeName="SCGName" columnNo="3"/>
    <column attributeName="clinicalStatus" columnNo="4"/>
    <column attributeName="clinicalDiagnosis" columnNo="5"/>
    <column attributeName="userEmail" fixedValue="forei@mail.nih.gov"/>
    <column attributeName="groupCollTime" columnNo="7"/>
    <column attributeName="groupRecTime" columnNo="8"/>
    <column attributeName="specCollTime" columnNo="7"/>
    <column attributeName="specRecTime" columnNo="8"/>
    <column attributeName="label" columnNo="9"/>
    <column attributeName="pathologicalStatus" columnNo="10"/>
    <column attributeName="tissueSite" columnNo="11"/>
    <column attributeName="quantity" columnNo="12"/>
    <column attributeName="availableQuantity" columnNo="12"/>
    <column attributeName="lineage" columnNo="13"/>
    <column attributeName="specimenType" columnNo="14"/>
    <column attributeName="tissueSide" columnNo="15"/>
    <column attributeName="collectionProcedure" fixedValue="Not Specified"/>
    <column attributeName="container" columnNo="16">
        <valueMapping>
            <valueMap fromValue="Red Top" ignoreCase="true" toValue="EDTA Vacutainer"/>
            <valueMap fromValue="Green Top" ignoreCase="true" toValue="Serum Separator Vacutainer"/>
            <valueMap fromValue="Blue Top" ignoreCase="true" toValue="Citrate Vacutainer"/>
        </valueMapping>
    </column>
    <column attributeName="receivedQuality" fixedValue="Not Specified"/>
    <column attributeName="groupActivityStatus" fixedValue="Active"/>
    <column attributeName="specimenActivityStatus" fixedValue="Active"/>
    <column attributeName="specimenAvailable" fixedValue="true"/>

</columnMap>

=== NCIP/catissue-utilities/tags/start/caTissueCoreLoader/examples/PatientTextMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<columnMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xml/caTissueTextMap.xsd" 
    headerRow="false"
    fileType="xlText">

    <dateFormat>MM/dd/yyyy</dateFormat>
    <rowClass>Participant</rowClass>
    <column attributeName="protocolTitle" fixedValue="Demo of collection protocol"/>
    <column attributeName="PPI" columnNo="7"/>
    <column attributeName="firstName" columnNo="1"/>
    <column attributeName="lastName" columnNo="2"/>
    <column attributeName="gender" columnNo="3">  
        <valueMapping>
            <valueMap fromValue="F" ignoreCase="true" toValue="Female Gender"/>
            <valueMap fromValue="M" ignoreCase="true" toValue="Male Gender"/>
            <valueMap fromValue="Female" ignoreCase="true" toValue="Female Gender"/>
            <valueMap fromValue="Male" ignoreCase="true" toValue="Male Gender"/>
        </valueMapping>
    </column>
    <column attributeName="birthDate" columnNo="6"/>
    <column attributeName="medicalRecordNumber" columnNo="7"/>
    <column attributeName="participantActivityStatus" fixedValue="Active"/>
    <column attributeName="regActivityStatus" fixedValue="Active"/>
    <column attributeName="siteName" fixedValue="Haven outpatients clinic"/>

</columnMap>

=== NCIP/catissue-utilities/caTissueCoreLoader/examples/FullPatientTextMap.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
   Copyright Washington University in St. Louis
   Copyright SemanticBits
   Copyright Persistent Systems
   Copyright Krishagni

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/catissue-utilities/LICENSE.txt for details.
L-->

<columnMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xml/caTissueTextMap.xsd" headerRow="false"
    fileType="xlText">

    <dateFormat>MM/dd/yyyy</dateFormat>
    <rowClass>Participant</rowClass>
    <column attributeName="protocolTitle" fixedValue="Demo of collection protocol"/>
    <column attributeName="PPI" columnNo="10"/>
    <column attributeName="firstName" columnNo="1"/>
    <column attributeName="lastName" columnNo="2"/>
    <column attributeName="middleName" columnNo="3"/>
    <column attributeName="gender" columnNo="4">
        <valueMapping>
            <valueMap fromValue="F" ignoreCase="true" toValue="Female Gender"/>
            <valueMap fromValue="M" ignoreCase="true" toValue="Male Gender"/>
            <valueMap fromValue="Female" ignoreCase="true" toValue="Female Gender"/>
            <valueMap fromValue="Male" ignoreCase="true" toValue="Male Gender"/>
        </valueMapping>
    </column>
    <column attributeName="ethnicity" columnNo="5"/>
    <column attributeName="race1" columnNo="6"/>
    <column attributeName="race2" columnNo="7"/>
    <column attributeName="birthDate" columnNo="10"/>
    <column attributeName="medicalRecordNumber" columnNo="11"/>
    <column attributeName="participantActivityStatus" fixedValue="Active"/>
    <column attributeName="regActivityStatus" fixedValue="Active"/>
    <column attributeName="siteName" fixedValue="Haven outpatients clinic"/>

    <column attributeName="vitalStatus" columnNo="16">
        <valueMapping>
            <valueMap fromValue="alive" ignoreCase="true" toValue="Alive"/>
            <valueMap fromValue="dead" ignoreCase="true" toValue="Dead"/>
            <valueMap fromValue="Deceased" ignoreCase="true" toValue="Dead"/>
            <valueMap fromValue="living" ignoreCase="true" toValue="Alive"/>
        </valueMapping>
    </column>
    <column attributeName="deathDate" columnNo="17"/>
    <column attributeName="sexGenotype" columnNo="18"/>
    <column attributeName="socialSecurityNumber" columnNo="19"/>

</columnMap>

=== NCIP/catissue-utilities/trunk/caTissueLoader/examples/LitsPatientColMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<columnMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xml/caTissueTextMap.xsd" 
    headerRow="true"
    fileType="xlText">

    <dateFormat>yyyyMMdd</dateFormat>
    <rowClass>Participant</rowClass>
    <column attributeName="firstName" columnNo="1"/>
    <column attributeName="lastName" columnNo="3"/>
    <column attributeName="middleName" columnNo="2"/>
    <column attributeName="birthDate" columnNo="7"/>
    <column attributeName="protocolTitle" fixedValue="LITS Interop demo protoco"/>
    <column attributeName="PPI" columnNo="14"/>
    <column attributeName="medicalRecordNumber" columnNo="14"/>
    <column attributeName="participantActivityStatus" fixedValue="Active"/>
    <column attributeName="regActivityStatus" fixedValue="Active"/>
    <column attributeName="siteName" fixedValue="LITS Interop Clinic"/>

</columnMap>

=== NCIP/catissue-utilities/caTissueCoreLoader/examples/childSpecimenTextMap.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
   Copyright Washington University in St. Louis
   Copyright SemanticBits
   Copyright Persistent Systems
   Copyright Krishagni

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/catissue-utilities/LICENSE.txt for details.
L-->

<columnMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xml/caTissueTextMap.xsd"
 headerRow="true"
 fileType="xlText">
    <dateFormat>MM/dd/yyyy</dateFormat>
    <rowClass>Specimen</rowClass>

    <column attributeName="parentSpecimenLabel" columnNo="1"/>
    <column attributeName="userEmail" fixedValue="forei@mail.nih.gov"/>
    <column attributeName="specCollTime" columnNo="3"/>
    <column attributeName="specRecTime" columnNo="4"/>
    <column attributeName="label" columnNo="5"/>
    <column attributeName="pathologicalStatus" columnNo="6"/>
    <column attributeName="tissueSite" columnNo="7"/>
    <column attributeName="quantity" columnNo="8"/>
    <column attributeName="availableQuantity" columnNo="8"/>
    <column attributeName="specimenType" columnNo="10"/>
    <column attributeName="tissueSide" columnNo="11"/>
    <column attributeName="collectionProcedure" fixedValue="Not Specified"/>
    <column attributeName="container" columnNo="12">
        <valueMapping>
            <valueMap fromValue="Red Top" ignoreCase="true" toValue="EDTA Vacutainer"/>
            <valueMap fromValue="Green Top" ignoreCase="true" toValue="Serum Separator Vacutainer"/>
            <valueMap fromValue="Blue Top" ignoreCase="true" toValue="Citrate Vacutainer"/>
        </valueMapping>
    </column>
    <column attributeName="receivedQuality" fixedValue="Not Specified"/>
    <column attributeName="specimenActivityStatus" fixedValue="Active"/>
    <column attributeName="specimenAvailable" fixedValue="true"/>

</columnMap>

=== NCIP/catissue-utilities/caTissueLoader/mappings/ethnicity/CDC Ethnicity Concepts.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
   Copyright Washington University in St. Louis
   Copyright SemanticBits
   Copyright Persistent Systems
   Copyright Krishagni

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/catissue-utilities/LICENSE.txt for details.
L-->

    <valueMapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../textdata/caTissueTextMap.xsd">
        <valueMap fromValue='Hispanic or Latino' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Spaniard' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Andalusian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Asturian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Castillian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Catalonian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Belearic Islander' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Gallego' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Valencian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Canarian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Spanish Basque' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Mexican' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Mexican American' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Mexicano' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Chicano' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='La Raza' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Mexican American Indian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Central American' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Costa Rican' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Guatemalan' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Honduran' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Nicaraguan' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Panamanian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Salvadoran' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Central American Indian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Canal Zone' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='South American' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Argentinean' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Bolivian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Chilean' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Colombian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Ecuadorian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Paraguayan' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Peruvian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Uruguayan' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Venezuelan' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='South American Indian' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Criollo' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Latin American' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Puerto Rican' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Cuban' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Dominican' ignoreCase='true' toValue='Hispanic or Latino'/>
        <valueMap fromValue='Not Hispanic or Latino' ignoreCase='true' toValue='Not Hispanic or Latino'/>
    </valueMapping>
